services:
  - type: web
    name: skillsnap-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: SANITY_PROJECT_ID
        sync: false
      - key: SANITY_DATASET
        sync: false
      - key: SANITY_TOKEN
        sync: false